version: "3"

services:
  node-app:
    command: npm start
    env_file:
      - ./.env
    ports:
      - "8000:8000"

    postgres:
      container_name: "dev_db"
      image: "postgres:12.6-alpine"
      env_file:
        - ./.env
      ports:
        - "5432:5432"
